# Generated by Django 3.2.9 on 2022-02-11 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('isSickLeave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Planifie', 'Planifié'), ('En cours', 'En cours'), ('Realise', 'Réalisé'), ('En pause', 'En pause'), ('Valide', 'Validé'), ('Livre', 'Livré')], default='En cours', max_length=200)),
                ('deleveryDate', models.DateField()),
                ('startingDate', models.DateField(default=django.utils.timezone.now)),
                ('stateOfProgress', models.PositiveSmallIntegerField(default=0)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=250)),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('duree', models.PositiveIntegerField()),
                ('startingDate', models.DateField(default=django.utils.timezone.now)),
                ('stateOfProgress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Planifie', 'Planifié'), ('En cours', 'En cours'), ('Realise', 'Réalisé'), ('En pause', 'En pause'), ('Valide', 'Validé'), ('Livre', 'Livré')], default='En cours', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.developer')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.task')),
            ],
        ),
        migrations.CreateModel(
            name='AssProject_Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.developer')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.project')),
            ],
        ),
        migrations.CreateModel(
            name='AssDev_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.developer')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.task')),
            ],
        ),
    ]
