# Generated by Django 3.2.9 on 2022-03-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssReport_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.report')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.task')),
            ],
        ),
        migrations.CreateModel(
            name='AssProject_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.project')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificateur.task')),
            ],
        ),
    ]
