# Generated by Django 3.2.9 on 2022-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0002_assproject_task_assreport_task_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fields',
            field=models.ManyToManyField(through='planificateur.AssDev_Task', to='planificateur.Developer'),
        ),
    ]
