# Generated by Django 3.2.9 on 2022-04-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ManyToManyField(through='planificateur.AssProject_Task', to='planificateur.Project'),
        ),
    ]
