# Generated by Django 3.2.9 on 2022-04-05 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0006_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
