# Generated by Django 3.2.9 on 2022-04-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0007_auto_20220406_1851'),
        ('planificateur', '0008_task_reports'),
    ]

    operations = [
    ]
