# Generated by Django 3.2.9 on 2022-04-06 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0009_merge_0007_auto_20220406_1851_0008_task_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reports',
        ),
        migrations.AlterField(
            model_name='project',
            name='deleveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startingDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
