# Generated by Django 3.2.9 on 2022-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificateur', '0011_remove_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reports',
            field=models.ManyToManyField(through='planificateur.AssReport_Task', to='planificateur.Report'),
        ),
    ]
